# Generated by Django 5.1.5 on 2025-02-03 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permisos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('cumplimiento', models.CharField(choices=[('<', 'Llegó Antes'), ('=', 'Llegó Exacto'), ('>', 'Llegó Después'), ('CUMPLIO', 'Cumplió'), ('NO_CUMPLIO', 'No Marcó')], default='NO_CUMPLIO', max_length=20)),
                ('total_horas', models.DurationField(blank=True, null=True)),
                ('justificado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='permisos.colaboradores')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_creadas', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_actualizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_asistencias',
            },
        ),
    ]
