# Generated by Django 5.1.5 on 2025-02-04 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_initial'),
        ('permisos', '0002_jefes_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id_sensor', models.CharField(max_length=20, unique=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeo_colaborador', to='permisos.colaboradores')),
            ],
        ),
    ]
