# Generated by Django 5.0.11 on 2025-02-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_employeemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_processed_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Biometric Sync Status',
                'verbose_name_plural': 'Biometric Sync Status',
            },
        ),
        migrations.DeleteModel(
            name='EmployeeMapping',
        ),
    ]
