# Generated by Django 5.0.11 on 2025-02-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_employeemapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeMapping',
        ),
    ]
