-- SQLite
select * from colaboradores;
select * from permisos;
select * from tipos_de_permisos;
select * from departamento;

select * from empresas;
select * from jefes;
select * from sucursal;
select * from unidad_de_negocio;

INSERT INTO tipos_de_permisos (nombre_permiso) VALUES
('enfermedad'),
('vacaciones'),
('defuncion'),
('Lactancia'),
('tiempo libre no remunerado'),
('Otros');

INSERT INTO departamento(nombre_departamento, fechacreacion, fechaactualizacion, estado) VALUES
('ACERO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('ADMINISTRACIÓN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('AUDITORÍA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('BODEGA CEDIS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('BODEGA CEMENTO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('BODEGA CERÁMICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('BODEGA HIERRO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('BODEGA MADERA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('BODEGA TIENDA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('CAJA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('COMPRAS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('CONCRETO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('CONTABILIDAD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('CRÉDITOS Y RECUPERACIONES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('D.O.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('FINANZAS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('GERENCIA GENERAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('GESTIÓN DE CALIDAD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('INGRESOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('INVENTARIO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('IT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('LEGAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('LIMPIEZA Y ASEO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('LOGISTICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('LOGÍSTICA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('MÉDICO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('MERCADEO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('MONITOREO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('OPERACIONES', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('PRODUCCIÓN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('RRHH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('SEGURIDAD', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('TALLER DE MANTENIMIENTO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('TESORERÍA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('VENTAS CAFETERÍA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('VENTAS CALL CENTER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('VENTAS CONTRATISTA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('VENTAS MAYOREO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('VENTAS PROYECTOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('VENTAS SUPER TIENDA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO');

INSERT INTO empresas (nombre_empresa, fechacreacion, fechaactualizacion, estado)
VALUES ('PROMACO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('IMPORTADORA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('PROMACO PRODUCCIÓN', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('URBANIZADORA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('TRITURADOS', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO');

INSERT INTO jefes (codigo, identidadjefe, nombrejefe, estado, fechacreacion, fechaactualizacion)
VALUES ('JF-1', '0601199700041', 'Lee Dongmin', 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)

INSERT INTO sucursal (nombre_sucursal, fechacreacion, fechaactualizacion, estado)
VALUES ('CHOLUTECA', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO'),
('SAN LORENZO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO');

INSERT INTO unidad_de_negocio (nombre_unidad_de_negocio, fechacreacion, fechaactualizacion, estado)
VALUES ('nrCHRRHH', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'ACTIVO');

INSERT INTO colaboradores (codigocolaborador, nombrecolaborador, estado, fechacreacion, fechaactualizacion, departamento_id, empresa_id, jefe_id, sucursal_id, unidad_de_negocio_id)
VALUES ('BJOR', 'BRAYAN JOSE ORTIZ RIVERA', 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3, 1, 1, 1, 1);
INSERT INTO colaboradores (codigocolaborador, nombrecolaborador, estado, fechacreacion, fechaactualizacion, departamento_id, empresa_id, jefe_id, sucursal_id, unidad_de_negocio_id)
VALUES ('KAMC', 'KAMILO ALEJANDRO MOLINA COREA', 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, 1, 1, 1);
INSERT INTO colaboradores (codigocolaborador, nombrecolaborador, estado, fechacreacion, fechaactualizacion, departamento_id, empresa_id, jefe_id, sucursal_id, unidad_de_negocio_id)
VALUES ('VSRC', 'VILMA STEPHANIE ROMERO COLADO', 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, 1, 1, 1, 1);


INSERT INTO permisos (colaborador, permiso_de, fecha_inicio, fecha_fin, motivo, comprobante, permiso_firmado, estado_inicial, estado_final, creado_por, fecha_creacion, modificado_por, fecha_modificacion, codigocolaborador_id, id_departamento_id, id_empresa_id, id_sucursal_id, id_tipo_permiso_id)
VALUES ('ALLAN ARNOLDO TORRES FLORES', 'Dias', '2025-01-25', '2025-01-30', 'Vacaciones pendiendtes', '', '', 'PENDIENTE', '', 'USER', CURRENT_TIMESTAMP, 'USER', CURRENT_TIMESTAMP, 2, 3, 1, 1, 2);