# Generated by Django 5.0.11 on 2025-01-27 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('hora_inicio_semana', models.TimeField()),
                ('hora_fin_semana', models.TimeField()),
                ('hora_inicio_sabado', models.TimeField(blank=True, null=True)),
                ('hora_fin_sabado', models.TimeField(blank=True, null=True)),
                ('hora_inicio_domingo', models.TimeField(blank=True, null=True)),
                ('hora_fin_domingo', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('cumplimiento', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registro_asistencias',
                'unique_together': {('empleado', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='RolAsignado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_asignados', to='roles.rol')),
            ],
            options={
                'db_table': 'roles_asignados',
                'unique_together': {('empleado', 'rol', 'fecha_inicio')},
            },
        ),
    ]
