# Generated by Django 5.0.11 on 2025-01-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_rename_actualizado_por_registroasistencia_modificado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8),
        ),
    ]
