# Generated by Django 5.0.11 on 2025-01-28 20:44

import Apps.permisos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=255)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Jefes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('identidadjefe', models.CharField(blank=True, max_length=13, null=True)),
                ('nombrejefe', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jefes',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=255)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='tiposPermiso',
            fields=[
                ('id_tipo_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_de_permisos',
            },
        ),
        migrations.CreateModel(
            name='Unidad_Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad_de_negocio', models.CharField(max_length=255)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
            ],
            options={
                'db_table': 'unidad_de_negocio',
            },
        ),
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigocolaborador', models.CharField(blank=True, max_length=20, null=True)),
                ('nombrecolaborador', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('INACTIVO', 'INACTIVO')], default='ACTIVO', max_length=8)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizacion', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='permisos.departamento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='permisos.empresas')),
                ('jefe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='permisos.jefes')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='permisos.sucursal')),
                ('unidad_de_negocio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='permisos.unidad_negocio')),
            ],
            options={
                'db_table': 'colaboradores',
            },
        ),
        migrations.CreateModel(
            name='registroPermisos',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('colaborador', models.TextField(blank=True, max_length=255, null=True)),
                ('permiso_de', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.TextField(max_length=255)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to=Apps.permisos.models.comprobante_path)),
                ('permiso_firmado', models.FileField(blank=True, null=True, upload_to=Apps.permisos.models.permiso_firmado_path)),
                ('estado_inicial', models.CharField(default='PENDIENTE', max_length=20)),
                ('estado_final', models.CharField(default='PENDIENTE', max_length=20)),
                ('creado_por', models.CharField(default='COLABORADOR', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('modificado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('codigocolaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisos.colaboradores')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisos.departamento')),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permisos.empresas')),
                ('id_sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permisos.sucursal')),
                ('id_tipo_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permisos.tipospermiso')),
            ],
            options={
                'db_table': 'permisos',
            },
        ),
    ]
