# Generated by Django 5.0.11 on 2025-02-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropermisos',
            name='descripcion',
            field=models.CharField(default='PENDIENTE', max_length=20),
        ),
    ]
