# Generated by Django 5.0.11 on 2025-02-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_registropermisos_descripcion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registropermisos',
            table='permisoos',
        ),
    ]
