# Generated by Django 5.0.11 on 2025-02-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0003_alter_registropermisos_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registropermisos',
            table='permisos',
        ),
    ]
