# Generated by Django 5.0.11 on 2025-02-04 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0004_alter_registropermisos_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='jefes',
            name='id_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permisos.colaboradores'),
        ),
        migrations.AddField(
            model_name='registropermisos',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='codigocolaborador',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
