# Generated by Django 5.0.11 on 2025-02-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0005_jefes_id_departamento_registropermisos_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jefes',
            name='id_departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='permisos.colaboradores'),
            preserve_default=False,
        ),
    ]
