# Generated by Django 5.0.11 on 2025-02-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0006_alter_jefes_id_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jefes',
            name='id_departamento',
        ),
    ]
