# Generated by Django 5.0.11 on 2025-02-04 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_jefes_usuario'),
        ('permisos', '0007_remove_jefes_id_departamento'),
    ]

    operations = [
    ]
