# Generated by Django 5.0.11 on 2025-02-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0008_merge_20250204_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='codigocolaborador',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
