# Generated by Django 5.0.11 on 2025-02-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0009_alter_colaboradores_codigocolaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropermisos',
            name='creado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
