# Generated by Django 5.0.11 on 2025-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0010_alter_registropermisos_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropermisos',
            name='descripcion',
            field=models.CharField(default='PENDIENTE', max_length=100),
        ),
    ]
