# Generated by Django 5.0.11 on 2025-02-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0011_alter_registropermisos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jefes',
            name='correo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
