# Generated by Django 5.0.11 on 2025-02-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0012_colaboradores_correo_jefes_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jefes',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
