# Generated by Django 5.0.11 on 2025-02-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0015_alter_registropermisos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registropermisos',
            options={},
        ),
    ]
